name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: 'maven'

      # mvnw의 실행권한 이슈 대비해서 bash로 실행
      - name: Build with Maven Wrapper
        run: bash mvnw -DskipTests clean package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: SamSkyBridge
          path: target/*.jar
